# Generated by Django 5.0.6 on 2024-05-10 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tech', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadership',
            old_name='name',
            new_name='position',
        ),
    ]
