# Generated by Django 5.0.6 on 2024-05-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tech', '0002_rename_name_leadership_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_name', models.CharField(max_length=250)),
                ('decision_number', models.IntegerField()),
                ('decision_text', models.CharField(max_length=250)),
            ],
        ),
    ]
