# Generated by Django 5.0.6 on 2024-05-12 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tech', '0003_standard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('characters', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Electronic_Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=250)),
                ('document_number', models.IntegerField()),
                ('document_category', models.CharField(max_length=250)),
                ('conditional_symbol', models.CharField(max_length=250)),
                ('document_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('email2', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('FIO', models.CharField(max_length=250)),
                ('e_mail', models.CharField(max_length=250)),
                ('text', models.CharField(max_length=250)),
                ('comments', models.CharField(max_length=250)),
                ('leadership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tech.leadership')),
            ],
        ),
    ]
